TRUNCATE TABLE village RESTART IDENTITY;
TRUNCATE TABLE subdistrict RESTART IDENTITY;
TRUNCATE TABLE district RESTART IDENTITY;
TRUNCATE TABLE state RESTART IDENTITY;
TRUNCATE TABLE country RESTART IDENTITY;